### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by AndrewSavetchuk** [AndrewSavetchuk/savetchuk.com-v1#1]
```scss
/**
 * Updates
 */
.updates {
  padding: 2rem 2.5rem;
  border-radius: 0.75rem;
  border: 2px solid #333;
}
```

```jsx
<div className={styles.mainColumn}>
  <section className={styles.updates}>Updates</section>
</div>
```
